### PR TITLE
Modify push script to create non-existent resource

### LINKED ISSUE #128: tx-push-src should handle new resource
When a new localization file is added to www it fails tx-push because it tries to update a non-existent resource on transifex.

### PR DESCRIPTION
**Pull request by chrisgarrity**
### Resolves

- Resolves #128 

### Proposed Changes

When trying to update a resource on transifex, it catches the file not found response and tries to create it instead.

This required adding a function that will return the correct file type for the resource based on the repository. Note, it will fail for new repositories. Also switched to using process.exitCode instead of process.exit to give async calls opportunity to finish.

Also checking in package lock changes, although they appear to be just changing. `http` to `https`

### Testing
I linked my local copy of www (develop branch) to the new version of l10n, then ran `npm run i18n:push`. The www script runs `tx-push-src` for all l10n files in www. Here's the output. Note that annual-report got the message about creating the resource instead of a 404 error:
```
$ npm run i18n:push

> www@1.0.0 i18n:push /Users/chrisg/Dev/scratch-www
> ./bin/tx-push-www --execute

pushing to transifex...
running command: $(npm bin)/tx-push-src scratch-website general-l10njson src/l10n.json
running command: $(npm bin)/tx-push-src scratch-website about-l10njson src/views/about/l10n.json
running command: $(npm bin)/tx-push-src scratch-website annual-report-l10njson src/views/annual-report/l10n.json
Transifex Resource not found, creating: annual-report-l10njson
running command: $(npm bin)/tx-push-src scratch-website boost-l10njson src/views/boost/l10n.json
running command: $(npm bin)/tx-push-src scratch-website camp-l10njson src/views/camp/l10n.json
...
```

### CODE REVIEW

File: scripts/tx-push-src.js [hunk 1]
```diff
@@ -41,11 +41,68 @@ const TX = new transifex({
...
+        // all the resources are android xml files
+        return 'ANDROID';
+    }
+    if (project === 'scratch-resources') {
+        // all the resources are Chrome format json files
+        return 'CHROME';
+    }
+    process.stdout.write(`Error - Unknown resource type for:\n`);
+    process.stdout.write(`  Project: ${project}, resource: ${resource}\n`);
+    process.exit(1);
```
Comment (chrisgarrity) [inline scripts/tx-push-src.js:75]: Note, I left this as `process.exit(1)` as this suggests an unknown 'project' or repository, and I really wanted it to fail right away.

File: scripts/tx-push-src.js [hunk 2]
```diff
@@ -41,11 +41,68 @@ const TX = new transifex({
...
-        process.exit(1);
+    if (err && err.response.statusCode !== 404) {
+        process.stdout.write(`Transifex Error: ${err.message}\n`);
+        process.stdout.write(
+            `Transifex Error ${err.response.statusCode.toString()}: ${err.response.body}\n`);
+        process.exitCode = 1;
+        return;
+    }
+    // file not found - create it, but also give message
+    if (err && err.response.statusCode === 404) {
```
Comment (kchadha) [inline scripts/tx-push-src.js:88]: This if can be combined w/the one above as a nested if so that we're only checking for `err` and comparing `err.response.statusCode` against 404 once. 

But also this is not an urgent/required change and doesn't need to block this PR.

**Review by kchadha — APPROVED** [review]
LGTM
